export default {
  en: {
    translation: {
      title: 'RSS aggregator',
      add: 'Add',
      label: 'RSS link',
      alreadyExists: 'RSS already exists',
      mustBeValid: 'Link must be valid URL',
      noValidRSS: 'The resource does not contain valid RSS',
      rssLoaded: 'RSS successfully loaded',
      feeds: 'Feeds',
      posts: 'Posts',
      show: 'Show',
      close: 'Close',
      readMore: 'Read more',
      networkError: 'Network error',
      unknownError: 'Unknown error. Something went wrong',
    },
  },
  ru: {
    translation: {
      title: 'RSS агрегатор',
      add: 'Добавить',
      label: 'Ссылка RSS',
      alreadyExists: 'RSS уже существует',
      mustBeValid: 'Ссылка должна быть валидным URL',
      noValidRSS: 'Ресурс не содержит валидный RSS',
      rssLoaded: 'RSS успешно загружен',
      feeds: 'Фиды',
      posts: 'Посты',
      show: 'Просмотр',
      close: 'Закрыть',
      readMore: 'Читать полностью',
      networkError: 'Ошибка сети',
      unknownError: 'Неизвестная ошибка. Что-то пошло не так.',
    },
  },
};
